import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SupabaseProvider from '@/supabase/provider'
import clsx from 'clsx'
import "./global.css";
import styles from "./page.module.css";
import Header from './_components/common/Header';
import ModalSetup from './_components/common/modal/ModalSetup';
import ReduxProvider from "./StoreProvider";
import ErrorBoundary from './_components/common/errorBoundary/Errorboundary';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <SupabaseProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* 루트 레이아웃 - 모바일 사이즈 레이아웃 */}
            <ErrorBoundary >
              <div className="container">
                <Header />
                <main className={styles.main}>
                  <ReduxProvider>
                    <div className ={styles.description}>{children}</div>
                  </ReduxProvider>
                </main>
                <ModalSetup />
              </div>
          </ErrorBoundary>
        </body>
      </html>
    </SupabaseProvider>
  )
}